version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

executors:
  mac-executor:
    macos:
      xcode: "13.4.1"
    working_directory: /Users/distiller/project

jobs:
  run-unit-tests:
    executor:
      name: mac-executor
    environment:
      FASTLANE_LANE: run_unit_tests
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout 
      - ruby/install-deps
      - run:
          name: "run unit tests"
          command: |
            "mkdir -p unit_tests_results"
            "bundle exec fastlane $FASTLANE_LANE"
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/unit_tests_results

  run-ui-tests:
    executor:
      name: mac-executor  
    environment: 
      FASTLANE_LANE: run_ui_tests
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout 
      - ruby/install-deps
      - run:
          name: "run ui tests"
          command: "bundle exec fastlane $FASTLANE_LANE"
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/ui_tests
workflows:
  build-and-run-tests:
    jobs:
      - run-unit-tests
      - run-ui-tests:
          requires:
            - run-unit-tests